<?php

namespace common\models;

/**
 * This is the model class for table "entity".
 *
 * @property int $id
 * @property string $cloned_id Ссылается на
 * @property string $letter Буква
 * @property string $type_code Тип сущности
 * @property string $name Название
 * @property string $description Описание
 *
 * @property Character[] $characters
 * @property EntityType $typeCode
 * @property Entity[] $entities
 */
class Entity extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'entity';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['description'], 'string'],
            [['letter'], 'string', 'max' => 1],
            [['type_code'], 'string', 'max' => 150],
            [['name', 'name_stressed'], 'string', 'max' => 250],
            [['type_code'], 'exist', 'skipOnError' => true, 'targetClass' => EntityType::className(), 'targetAttribute' => ['type_code' => 'code']],
            [['cloned_id'], 'exist', 'skipOnError' => true, 'targetClass' => Entity::className(), 'targetAttribute' => ['cloned_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
			'id' => 'ID',
			'letter' => 'Буква',
			'type_code' => 'Тип сущности',
			'name' => 'Название',
	        'name_stressed' => 'С ударением',
			'description' => 'Описание',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCharacters()
    {
        return $this->hasMany(Character::className(), ['entity_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTypeCode()
    {
        return $this->hasOne(EntityType::className(), ['code' => 'type_code']);
    }

    /**
     * @inheritdoc
     * @return EntityQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new EntityQuery(get_called_class());
    }

	public static function findOne($condition, $param = null)
	{
		if(empty($param))
			return parent::findOne($condition); // TODO: Change the autogenerated stub
		else
		{
			return self::find()
				->selectTypeName()
				->where(['id' => $condition])
				->one();
		}
	}
}